spring:
  application:
    name: spring-boot-admin
  boot:
    admin:
      ui:
        brand: "PSF"
        title: "PSF Spring Boot Admin"
  cloud:
    kubernetes:
      catalog-services-watch:
        enabled: true
        catalogServicesWatchDelay: 5000
      discovery:
        service-labels:
          type: manage

server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /manage
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
  server:
    port: 8081

logging:
  level:
    org.springframework.cloud.kubernetes: DEBUG
    de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener: DEBUG